name: Add issues to the issue tracker project

on:
  issues:
    types:
      - opened
      - reopened
  workflow_call:
    secrets:
      ADD_TO_PROJECT_PAT:
        required: true

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/DigitalShoestringSolutions/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
